services:
  db:
    image: postgres:16-alpine
    container_name: siart-db
    environment:
      POSTGRES_DB: siart_db
      POSTGRES_USER: siart_user
      POSTGRES_PASSWORD: siart_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - siart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siart_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  rtmp:
    image: alqutami/rtmp-hls:latest
    container_name: siart-rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - siart-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siart-web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - siart-network
    environment:
      NEXT_PUBLIC_HLS_BASE_URL: http://localhost:8080/hls
      DATABASE_URL: postgresql://siart_user:siart_pass@db:5432/siart_db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  siart-network:
    driver: bridge
